driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: ~/path/to/your/private/aws/key.pem

verifier:
  name: terraform
  groups:
    - name: default
      backend: local
      controls:
       - bucket
      attrs_outputs:
       test_bucket_name: bucket_name

suites:
  - name: default