driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  groups:
    - name: default
      backend: local
      controls:
       - bucket

platforms:
  - name: terraform

suites:
  - name: default