apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::238073932035:role/eks-node-eks-test-role
      username: system:node:ip-192-198-4-229.ec2.internal
      groups:
        - system:bootstrappers
        - system:nodes